name: Keep my Duolingo streak

on:
  schedule:
    - cron: '0 0 * * *' # 6 AM Asian time
    - cron: '0 6 * * *' # 12 PM Asian time
    - cron: '0 12 * * *' # 6 PM Asian time
    - cron: '0 15 * * *' # 9 PM Asian time

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Generate Random Delay
        id: random-delay
        run: echo "delay=$((RANDOM % 150))" >> $GITHUB_OUTPUT  # Generates a random number

          # Your action commands go here
      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: ${{ steps.random-delay.outputs.delay }}
